### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#16]
## Userstory

As a User
I want to have a navigation
so that I can have quick access to important pages

## Description

A Navigation menue  and some buttons will be added so that the landing page has a cleaner appearance.
Also user will be able to  access new functionality. 
![Untitled-2022-06-24-1129](https://user-images.githubusercontent.com/104091064/175540525-773a6108-a4e7-4034-9f9d-782c4f8c1ee0.png)

## AC
- [ ] access different pages 
- [ ] routing is working correctly
- [ ] singlepage application

## Tasks
- [ ] create new branch
- [ ] add router
- [ ] add navmenue 
- [ ] add button for e.g. add new bankaccount and and new transaction

## Complexity
easy

**Comment by lkk95** [comment]
Good job on this user story!:thumbsup:
