### ISSUE TITLE
Edit Bank Account

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#18]
## User Story

As a User
I want to edit the bank account 
so that I can change the information 

## Description

onClick the user is able to edit a bank account. There will be the possibility to change the name of the account and it´s bank and also update the starting value. 
![Untitled-2022-06-27-1028](https://user-images.githubusercontent.com/104091064/176144305-69fee89e-063d-43c4-a91b-3f53b79c28e6.png)

## AC

- [x] edit button will be added on every bank account
- [x] user is able to update the selected bank account 
- [x] update will be displayed on dashboard
 

## Tasks

- [x] create new branch
- [x] add input form with account name, bank name and value
- [x] the form will be pre-filled with the current information on that bank account  
- [x] create a new react route

## Complexity 
medium  

## depens on 
#4
