### ISSUE TITLE
Remove a Transaction

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#19]
## User Story
As a User
I want to delete a transaction
so that I can undo previous transaction

## Description
A delete button will be added to the transactions. 
![Untitled-2022-06-27-1022](https://user-images.githubusercontent.com/94990541/176142417-9f43f3ab-8278-4efc-b3d1-695f7f38052f.png)

## AC

- [x] Remove the selected transaction from the shown list by clicking on the delete button

## Tasks
- [x] create a new branch
- [ ] create storybook
- [x] add new button to transactions
- [x] add `onClick` event for deleting transaction

**Comment by marcbendixen** [comment]
Hey 👋 
Looks good to me.

Just an idea: One thing you could add is some kind of confirmation dialog before deleting a transaction.
So the user doesn't delete unintentionally 🙂
