### ISSUE TITLE
Navigate to Transactions Button

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#25]
## User Story
As a User
I want to click on a specific bank account
so that I can easily navigate to its' transaction history. 

## Description
Depends on #5 #4 #16
Add a button to the bank accounts on the dashboard so it navigates to the specific transaction history.

![Untitled-2022-06-27-1022(1)](https://user-images.githubusercontent.com/94990541/176209627-76368a94-e8b2-4206-b07c-8687a3fbecbc.png)

## AC

- [x] add Button to bank account elements
- [x] Only the transactions of a specific account get shown onClick
- [x] Add a back button to enable the user to return to the dashboard 

## Tasks

- [x] create a new branch
- [x] add navigation to bank account elements
- [x] filter entries according to clicked bank account 
- [x] show filtered entries on transaction history page 

## Complexity
Medium
