### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#3]
### User Story
<hr/>
As a user
I want a page that lists my bank accounts
so that I can have a quick overview over them.

### Description
<hr/>
The page contains a list of different bank accounts.
![Dashboard](https://user-images.githubusercontent.com/94990541/174667091-a98a873d-c20d-4e55-b847-bda9b050871d.png)

### AC
<hr/>
- [ ] page that contains a list of different bank accounts

### Tasks
<hr/>
- [ ] create a new branch
- [ ] create a new page
- [ ] add a list with different items that resemble bank accounts

### Complexity 
<hr/>
Easy
