### ISSUE TITLE
Categories shown on Transactions

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#35]
## User Story

As a User
I want to be able add a category to my transaction
So that I know where my expenses are going

## Description
The user should be able to add a category to the transaction and it will displayed on the transaction. 

## AC

- [x] category will be visible on transaction
- [x] user can select the category

## Tasks
 
- [x] create new branch
- [x] refactor datalist to select at the dropdown menu
- [x] add element on transaction to show category

## Complexity
very small

 ## depends on
# 9
