### ISSUE TITLE
Routing to transaction history after editing a transaction

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#36]
## User Story

As a User 
I want to be redirected to transaction history after editing a transaction
so that can see the changes I made immediately

## Description
After clicking on the submit button from the edit-transaction-form, the user should be redirected to the transaction history. 

## AC

- [x] onClick the form will closed
- [x] transaction history should be visible after submit 

## Tasks

- [x] create new branch
- [x] create a route to transaction history

## Complexity 
very small 

## depends on 
#21
