### ISSUE TITLE
Add notifications when editing content

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#38]
## User Story
As a User 
I want to be notified when I successfully edited my data
So that I know that my changes have been submitted. 

## Description
A small popup window will open and tell the user if their data has been successfully edited or if something went wrong.

## AC

- [ ] pop-up window on submit

## Tasks

- [ ] create a new branch
- [ ] implement React Toastify
- [ ] set up notifications for editing bank accounts and transactions

## Complexity
M

Depends on
#37
