### ISSUE TITLE
Add Persist

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#39]
## User Story
As a User 
I want to be able to save my data
So that my data does not get lost when I refresh the page.

## Description
The user should be able to refresh the site without losing any data they added/edited.

## AC
- [x] data should not vanish on refresh
- [x] data should be stored locally

## Tasks
- [x] create a new branch
- [x] implement persist

## Complexity
S

depends on
#10
