### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#4]
## User Story

As a user
I want a page that lists my bank accounts
so that I can have a quick overview over them.

## Description

The page contains a list of different bank accounts.
![Dashboard](https://user-images.githubusercontent.com/94990541/174667091-a98a873d-c20d-4e55-b847-bda9b050871d.png)

## AC

- [x] page that contains a list of different bank accounts

## Tasks

- [x] create a new branch
- [x] create component test for feature
- [x] create feature in storybook
- [x] create a new page
- [x] add a list component with different items that resemble bank accounts 
- [x] add basic styling

## Complexity 

Easy

**Comment by mbosselmann** [comment]
Hey Dana and Philipp,
I really like your user story! ❤️ You rock! 🪨 
I only have one idea: You could add Storybook and Testing as separate tasks for this feature. 💪

**Comment by dananhsl** [comment]
Thanks for your feedback Mareike! We will add storybook aswell as testing to the tasks, thanks for the reminder!
