### ISSUE TITLE
Filter transaction by categories and date

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#40]
## Userstory

As a User
I want to filter my transaction
so that is more easy to find specific transactions

 ## Description
Select a date and category filter on transactions to get easy access to specific transactions
![Untitled-2022-07-05-0134](https://user-images.githubusercontent.com/104091064/177294189-a3119120-d6f6-44ce-9ee9-453fc6f85999.png)

## AC

- [x] date filter is working
- [x] category filter is working
- [ ] both filters can be used together

## Tasks
 
- [x] create new branch
- [x] add date filter
- [x] add category filter
- [ ] implement logic so both filters work together

## Complexity
large

## depends on
#35
