### ISSUE TITLE
Add income/expense

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#41]
## User Story
As a User 
I want to be able to differentiate my transactions
So that I can choose whether it's an income or expense.

## Description
Two buttons will be added to the transaction form, giving the user the ability to choose whether the transaction will be an income or an expense.
![Untitled-2022-07-05-0904](https://user-images.githubusercontent.com/94990541/177291398-d62bfad2-4aa7-47e9-a94c-8c700484bc88.png)

## AC

- [ ] account balance will be updated according to the transaction that has been made

## Tasks

- [ ] create a new branch
- [ ] put two buttons on transaction form 
- [ ] write counter logic for adding/substracting transaction
- [ ] onClick addition or substraction will be chosen 
- [ ] update account balance 

## Complexity
M
