### ISSUE TITLE
Add a cancel button to forms

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#49]
## User Story
As a User
I want to be able to navigate to the previous page
so that I can cancel submitting unwanted changes.

## Description
A back-button will be added to the transaction and bank account forms to allow the user to cancel submitting their changes. 

## AC

- [ ] added button top left corner
- [ ] let the user return to previous page without submitting any changes 

## Tasks

- [ ] create a new branch
- [ ] add two buttons
- [ ] useNavigate to navigate to previous page

## Complexity 
medium
