### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#5]
## Userstory

As a User 
I want see a list of all transactions of one bank account 
so that I can have a detailed overview 

## Description
The Page contains a list transactions on a specific bank account
![Dashboard(1)](https://user-images.githubusercontent.com/94990541/174780730-a3d6dc5e-dba2-46d5-934b-1850a38c4fce.png)
The dashboard is part of another user story. #4 

## AC

- [ ] page that contains a list of transactions for one specific bank account

## Tasks

- [ ] create a new branch
- [ ] create a new page
- [ ] add a list component with different items that resemble transaction history
- [ ] add basic styling

## Complexity 

easy

**Comment by dananhsl** [comment]
Hey Mareike! We originally wanted to build it as a SPA first so the User can take a look at everything and then add the navigation later on in a separate user story. 
Would that make sense or should we add the navigation right away? We have a burger menu, interaction with the accounts and buttons planned for navigating, so it would be enough to create another story.

**Comment by mbosselmann** [comment]
Hi Dana and Philipp,
looks good! 👍 I approve your user story. :)

**Comment by dananhsl** [comment]
Thanks for your feedback Mareike!
