### ISSUE TITLE
Task: Implement Testing for Transaction Component

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#51]
## Developer Story

As a Developer
I want to test components 
so I make sure the work properly

## Description
Writing Testing for transaction component. 

## AC
- [ ] pop-up window on submit

## Tasks
 
- [ ] create a new branch
- [ ] implement test for transaction 

## Difficulty 
s
