### ISSUE TITLE
Analysis Page

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#57]

**Comment by p-enz** [comment]
## User Story

As a User
I want to have an graphical overview about all my Transactions
so that easily see where my money is going.

## Description

A new page will be added where the user sees a Chart, that shows all transactions filtered by category. 
![Untitled-2022-07-11-2004](https://user-images.githubusercontent.com/104091064/178711698-ab915188-8d88-4e79-868f-ec2cd9a77a7a.png)


## AC

- [ ] new navigation link to analyse page
- [ ] chart will be displayed correctly


## Tasks
 
- [ ] create new branch
- [ ] implement react charts
- [ ] use filterAllTransaction to fill data to the chart


## Complexity
m 

 ## depends on
#55
