### ISSUE TITLE
Task: Remove unrequired Files

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#58]
## Developer Story

As a Developer
I want to remove unrequired files
so that the project is easier to maintain

## Description

Unrequired files will be deleted from the template.

## AC

- [x] files deleted

## Tasks

- [x] delete unneeded components
- [x] delete unneeded pages
- [x] delete storybook files

## Difficulty 
s
