### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#60]
## User Story
As a User
I want the app that I'm using to be styled
so that I enjoy using it.

## Description
The app design will be refactored completely and will be divided into multiple tasks. 

## AC

- [ ] the app should look nice and have multiple themes

## Tasks
- [ ] create new branch
- [ ] create tasks for styling the components

**Comment by JessicaLoers** [comment]
**hello @dananhsl @p-enz** 
I am very curious about the result 🤩

Some suggestions:
- You could also think again about your global styles.
**Value Proposition + AC**
   - Please describe both more detailed. **What is the benefit for the user?** For example:  _"being able to use the app intuitively"_. Good design ist invisible 😶‍🌫️, the user doesn't notice it. Everything else is mostly a matter of taste. 
   - You could also mention the topic of accessibility as an AC.
   
 Take a moment to think about it again, before you get started.

**Comment by dananhsl** [comment]
Hey Jessica, 
I implemented the changes, would you be so kind as to take another look? :D

**Comment by JessicaLoers** [comment]
👍
