### ISSUE TITLE
Task: Test Form Transaction

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#64]
## Developer Story

As a Developer
I want to test components 
so I make sure the work properly

## Description
Writing Testing for transaction component. 

## AC
- [ ] test cases work correctly

## Tasks
 
- [ ] create a new branch
- [] implement test for form transaction 

## Difficulty 
m
