### ISSUE TITLE
[onHold] Task: Test Form Account

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#66]
## Developer Story

As a Developer
I want to test components 
so I make sure the work properly

## Description
Writing Testing for form account  component. 

## AC
- [ ] test cases work correctly

## Tasks
 
- [ ] create a new branch
- [ ] implement test for Form Account  

## Difficulty 
m
