### ISSUE TITLE
Task: Test Dashboard Component

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#68]
## Developer Story

As a Developer
I want to test components 
so I make sure the work properly

## Description
Writing Testing for Dashboard Component 

## AC
- [ ] test cases work correctly

## Tasks
 
- [ ] create a new branch
- [ ] implement test for dashboard component

## Difficulty 
s
