### ISSUE TITLE
Task: Update Test Account

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#69]
## Developer Story

As a Developer
I want to test components 
so I make sure the work properly

## Description
Writing Testing for account component. 

## AC
- [x] test cases work correctly

## Tasks
 
- [x] create a new branch
- [x] refactor account test

## Difficulty 
s
