### ISSUE TITLE
add new Bank Account

### ISSUE THREAD

**Issue by dananhsl** [dananhsl/capstone-project#7]
## Userstory

As a User 
I want to add a new bank accounts
so that I have all my bank accounts in one place

## Description
A form will be added below the dashboard view to add new bank accounts.
The data will not be saved and disappear on refresh.
The dashboard will be added in #4 

![Dashboard(2)](https://user-images.githubusercontent.com/94990541/174830823-cdc7dc58-6128-4c8d-8064-5dc5e7ca9943.png)

## AC

- [x] add a form component
- [x] dynamically add new bank accounts on submit

## Tasks

- [x] create a new branch
- [ ] create component test
- [ ] create storybook
- [x] create a form component
- [x] create an input field for the account name
- [x] create an input field for the bank name
- [x] create an input field for the account value
- [x] create a submit button
- [x] add basic styling

## Complexity 

medium

**Comment by lkk95** [comment]
Hey Dana and Philipp, this story looks very good! :)
I just have one suggestion: It is not quite clear where you save the data from your inputs or if this is a part of another user story. Maybe you could add that.

**Comment by dananhsl** [comment]
Hey Laura, thanks for your review! We will probably add a local storage later on, for now the data will just disappear after the refresh. :) But i will add it to the story!
