### ISSUE TITLE
Task: Test Navigation Component

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#70]
## Developer Story

As a Developer
I want to test components 
so I make sure the work properly

## Description
Writing Testing for navigation component. 

## AC
- [ ] test cases work correctly

## Tasks
 
- [ ] create a new branch
- [ ] implement test for navigation

## Difficulty 
m
