### ISSUE TITLE
Task: Refactoring Naming on Components, Variables, Functions

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#71]
## Developer Story

As a Developer
I want to refactor my project
so that it´s easier to maintain 

## Description
Refactor naming on some Components, Variables and Functions to make the code easier to understand and maintain

## AC
- [ ] app is working 
- [ ] naming is less complicated 

## Tasks
 
- [ ] create a new branch
- [ ] go through files and rename most of it

## Difficulty 
m
