### ISSUE TITLE
Remove a Bank Account

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#8]
## Userstory

As a User
I want to delete the bank account
so that I can sort out unneeded bank accounts

## Description
A Delete-Button will be added on the Bank Account component.
![Untitled-2022-06-20-2340fenj](https://user-images.githubusercontent.com/104091064/174836576-2d5b4b6b-2c21-4991-88a3-ed9fd0d65407.png)

## AC
- [x] Remove the selected bank account from the shown list by clicking on the delete button

## Tasks
- [x] create a new branch
- [x] create storybook
- [x] add onClick event for deleting the bank account 

## Complexity 
easy
