### ISSUE TITLE
new Transaction

### ISSUE THREAD

**Issue by p-enz** [dananhsl/capstone-project#9]
## User Story

As a User
I want to create a transaction 
so that this is added to my bank account

## Description

onClick the user is able to add a new transaction to a specific bank account.
The user will be able to categorize transactions and add a note to it. The Categories will be selectable with a dropdown menue.
![Untitled-2022-06-22-1041](https://user-images.githubusercontent.com/104091064/174991223-6cfb6b2c-2032-4832-b5d7-45d658f58fe7.png)

## AC

- [x] new transfer will be added to a list

## Tasks

- [x] create new branch
- [x] add an input form with note, change value and category 
- [x] create the dropdown menu for categories

## Complexity 
medium

## depens on 
#5

**Comment by desplodur** [comment]
Hey,

**Comment by UlrikeWerner** [comment]
lgtm
